# Generated by Django 4.0.5 on 2022-06-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
